import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Outfit } from 'next/font/google'
import { Urbanist } from 'next/font/google'
import { Young_Serif } from 'next/font/google'
import { Poppins } from 'next/font/google'
import '@fontsource/poppins/600.css';
import '@fontsource/urbanist';
import '@fontsource/finger-paint';
import '@fontsource/outfit';
import '@fontsource/young-serif';


const inter = Inter({ subsets: ['latin'] })
const outfit = Outfit({ subsets: ['latin'], weight:'800' })
const poppins = Poppins({ subsets: ['latin'], weight:'600' })
const urbanist = Urbanist({ subsets: ['latin'], weight:'800' })



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
