import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@fontsource/outfit';
import '@fontsource/young-serif';
import '@fontsource/playfair-display';
import '@fontsource/martian-mono';
import '@fontsource/major-mono-display';
import '@fontsource/ibm-plex-mono';
import '@fontsource/urbanist';


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
